### ISSUE TITLE
Implement Feature - Configurable Comment Editing Window (#NEW_FEATURE) by Usman Ghias

### ISSUE THREAD

**Issue by UsmanGhias** [isso-comments/isso#1034]
# Follow me on [GitHub](https://github.com/usmanghias) and Visit my [Web App](https://codcrafters.org)

**Labels:** feature, enhancement

**Description:**

The current implementation of Isso allows users to edit their comments within 15 minutes by default. This feature request proposes adding configuration options to customize this edit window.

**Benefits:**

* **Flexibility:** This allows website owners to adjust the edit window based on their specific needs. 
* **Security:** A shorter window might be desirable for high-traffic sites to prevent potential misuse.
* **User Experience:**  A longer window could be better for smaller, more intimate communities.

**Comment by UsmanGhias** [comment]
**Proposed Solution:**

1. Introduce a new configuration option in the `isso.cfg` file (or environment variable) to define the edit window duration in minutes.
2. Update the Isso server code to respect the configured edit window duration during comment edit attempts.
3. Consider adding a user-friendly interface (optional) for website admins to adjust the edit window via the Isso admin panel (if applicable).

**Current Behavior:**

Users can only edit their comments within 15 minutes of posting.

**Desired Behavior:**

Users can edit their comments within a configurable time window defined by the website owner.

**Additional Notes:**

* This feature would be a valuable addition to Isso, offering greater control over comment management.
* Open to discussion on the best implementation approach (configuration file option vs environment variable).

**Please let me know your thoughts and if others have encountered this limitation!**

**Comment by ix5** [comment]
Please follow the provided issue template and refrain from self-promotion.

As for the request by itself, we have thought about adding a proper user management system which would partially address issues of not being able to edit/delete a comment when the cookie expires.
