### ISSUE TITLE
[feature] Sort by newest/highest votes

### ISSUE THREAD

**Issue by posativ** [isso-comments/isso#4]

**Comment by Schweinepriester** [comment]
push :)

**Comment by georg90** [comment]
+1!!

**Comment by lost-carrier** [comment]
+1

**Comment by blatinier** [comment]
#322 tried to implement it but it fails due to sorting happening on client side, and pagination retrieval on the server side. It needs a bit more work.

**Comment by angristan** [comment]
A quick and dirty workaround: add `'asc': 0` here:

https://github.com/posativ/isso/blob/master/isso/views/comments.py#L752#L757

**Comment by mdehghani65** [comment]
plz somebody implement this as soon as possible. because specially when you limit the default comment numbers to be shown , it is very logical that the latest ones should be shown first.

**Comment by ggtylerr** [comment]
+1 this. Sad to see this is still an issue after over a decade, even the workaround has problems (replies are sorted in reverse too.)

**Comment by pkvach** [comment]
I'm currently working on this feature. 
I hope to finish the PR soon. I'll link it to this issue.
