### ISSUE TITLE
Prevent clicking submit twice

### ISSUE THREAD

**Issue by cjquines** [isso-comments/isso#913]
In the following logic, we clear the comment text or close the box only after the API call succeeds. But if the API call takes a few seconds, then excited users might press "submit" multiple times. Maybe disable clicking the "submit" button as soon as it's clicked the first time?

https://github.com/posativ/isso/blob/10e5a90df94d8f1b710f5b1d9a22172fb84e8978/isso/js/app/isso.js#L109-L122

**Comment by akshatakulkarni25** [comment]
hey @ix5 can i work on this issue

**Comment by ix5** [comment]
> hey @ix5 can i work on this issue

Great, go for it!

**Comment by cjquines** [comment]
thanks for fixing this @pkvach !

**Comment by pkvach** [comment]
> thanks for fixing this @pkvach !

Thanks, glad to help.
